### ISSUE TITLE
[Feature request] Option to make coordinate offset constant and have a default

### ISSUE THREAD

**Issue by Gaming32** [cavallium/CoordinatesObfuscator#11]
It's too bad that this plugin's goal is only to obfuscate player coordinates. It would be really useful to be able to use this as a coordinate offset plugin. One use case for this is making it appear so that a server's spawn in the millions would appear like 0,0 (a use case of that would be GeyserMC, because Bedrock Edition breaks at large coordinates). I actually privately forked this repo to make this ability a reality, but the fork bit the dust when 1.18 rolled around.

**Comment by cavallium** [comment]
If you open a pull request with this feature I will merge it

**Comment by cavallium** [comment]
Please, update to https://github.com/joshuaprince/CoordinateOffset
