### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by stitchinger** [cavallium/CoordinatesObfuscator#15]
Hello, 
do I have to do something else than install the plugin and protocolLib to get it to work?
The plugin also spams the console. Is that normal behaviour?

**Comment by cavallium** [comment]
send me the error

**Comment by stitchinger** [comment]
I just had to reinstall it after I kicked it before. I need protocolLib right? You should make that more obvious somehow.
Right now it doesnt even throw errors. It just does nothing.
This are the only logs: 
[CoordinatesObfuscator] Setting player coordinates offset
[CoordinatesObfuscator] Deleting player coordinates offset (globally)

To be honest I dont even know what this plugin is supposed to do. 
Will your plugin obfuscate a players coords, when they use Xeros Maps for example?

**Comment by cavallium** [comment]
Done. I've fixed the bug
https://github.com/cavallium/CoordinatesObfuscator/releases/download/v1.4.6/CoordinatesObfuscator-1.4.6-fix.jar

**Comment by stitchinger** [comment]
Wow, thank you very much. Gonna try it now.
Does that mean, that your plugin is doing, what I think it does?^^
