### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by stitchinger** [cavallium/CoordinatesObfuscator#17]
Hello, I get some errors from this plugin in the console.
https://pastebin.com/acVzRa0L

**Comment by cavallium** [comment]
What server/version are you using?

**Comment by stitchinger** [comment]
Im using spigot 1.18.2

**Comment by cavallium** [comment]
Fixed in https://github.com/cavallium/CoordinatesObfuscator/releases/tag/v1.4.7

**Comment by stitchinger** [comment]
Thx mate :)
