### ISSUE TITLE
1.19.4 Compatibility

### ISSUE THREAD

**Issue by UmpquaRiver** [cavallium/CoordinatesObfuscator#18]
I updated my paper spigot server to 1.19.4 and installed the latest version of this plugin alongside a dev version of ProtocolLib. In 1.19.3, there were some issues with mobs disappearing occasionally and errors in the console. In 1.19.4, no mobs appear and the aforementioned errors still appear in console.

Thank you for the work that's been done to keep this up to date so far. (=

**Comment by UmpquaRiver** [comment]
All good, just noting the problem as it's an open project. I hope someone will jump in, as has happened before. I would myself if I had the know how. =/

**Comment by cavallium** [comment]
Thanks @joshuaprince for your help!
