### ISSUE TITLE
Vanilla worldborders experience cosmetic and functional issues

### ISSUE THREAD

**Issue by Sabinno** [cavallium/CoordinatesObfuscator#2]
This plugin does not support vanilla world borders and, both cosmetically and functionally, breaks them severely. The red vignette is perpetually present on worlds with tightly confined worldborders. At the edges of the worldborder, the worldborder wall cannot be seen. Additionally, the client does not stop the player from traveling beyond the worldborder. Could the worldborder data sent to the player potentially be shifted with coordinates to resolve this?

https://wiki.vg/Protocol#World_Border

**Comment by Cavallium** [comment]
If you set the offset of the worldborder, the player can calculate the real coordinates.

**Comment by Cavallium** [comment]
If you find a solution that is mathematically secure I'll fix this.

**Comment by Sabinno** [comment]
I can certainly see where you're coming from, having thought it over myself.

However, the likelihood of a Minecraft player performing some kind of packet analysis to determine relative coordinates based on the worldborder info is... Just about zero. Not even hacked clients (e.g. Wurst) check that kind of stuff afaik.

I definitely understand the importance of mathematical security for this plugin, but we're not talking about securing passwords -- we're talking about obscuring world coordinates within a video game.

I feel like an option to enable worldborder shifting would be fantastic, as it saves me from having to install yet another plugin just for a feature that already exists in vanilla Minecraft.

**Comment by Cavallium** [comment]
The problem is that reading the worldborder packet is the easiest thing in the world. It contains the precise coordinates. It's about doing a simple subtraction.

**Comment by Cavallium** [comment]
The easiest thing that you can do is reducing the worldborder by 1 million, that's a very small number compared to the already enormous maximum world size.

**Comment by AoElite** [comment]
How about just adding a configuration option to fix this?

**Comment by Cavallium** [comment]
Yes, it's feasible, but I don't have time to do that. If someone opens a pull request with that feature I'll merge it.

**Comment by Gaming32** [comment]
I feel like a use case for this without causing security harm are for when the plugin wouldn't be used for security with #11.

**Comment by cavallium** [comment]
The latest release fixes the world border issues

**Comment by wiselder** [comment]
It doesn't work anyway (v1.4.6).
