### ISSUE TITLE
[CoordinatesObfuscator] Failed to register events 

### ISSUE THREAD

**Issue by stitchinger** [cavallium/CoordinatesObfuscator#20]
Hello, seems like this plugin is not working on paper 1.19.4. Coordinates stay the same after death or relog.
I get the following error on the startup of the server:
[12:32:55 ERROR]: [CoordinatesObfuscator] Failed to register events for class org.warp.coordinatesobfuscator.CoordinatesObfuscator because io/papermc/paper/threadedregions/scheduler/ScheduledTask does not exist.

Edit: After some testing, I noticed that the coords only get scrambled after the server restarts. Hope you can help me with this. Your plugin is super important for my server

**Comment by Vlad0Crystal** [comment]
Same thing, just wanted to let you know that  the plugin stopped working 
![image](https://user-images.githubusercontent.com/47213885/233633275-48a8b603-1be0-4c7e-b722-d41a2bfe35ef.png)

**Comment by cavallium** [comment]
Fixed in 1.4.10

**Comment by Vlad0Crystal** [comment]
> Виправлено в 1.4.10

So fast, thank you =)

**Comment by stitchinger** [comment]
Thanks for the quick fix^^
