### ISSUE TITLE
Coords dont get randomized on death, netherportal, teleport

### ISSUE THREAD

**Issue by stitchinger** [cavallium/CoordinatesObfuscator#21]
Hi, im running 1.4.10 on 1.19.4 paper and noticed that the coords dont get randomized, when a players died, respawned or changed world.
It seems to only randomise the coords, when a player leaves the server and joins again. 

Edit: I also noticed that setMaxWorldBorder is now calling itself instead of setMaxWorldBorderSync. Is this intended?

**Comment by cavallium** [comment]
Thanks!
