### ISSUE TITLE
Spectator gamemode randomised cords only

### ISSUE THREAD

**Issue by gamer50082** [cavallium/CoordinatesObfuscator#27]
Make it so if user is in creative or spectator mode it randomised their cords only and survival players get real cords

make it a configuration

**Comment by Royalflamejlh** [comment]
Would also like this but was wondering if this plugin could be used as some sort of api to set whether or not a player see's obfuscated coords on a player to player basis.

**Comment by joshuaprince** [comment]
I made a fork of this plugin called [CoordinateOffset](https://github.com/joshuaprince/CoordinateOffset) that allows much more configuration into how coordinates are obfuscated. There is no direct gamemode hook, but it does allow configuration by world, player, and permission, as well as exposing a plugin API.
