### ISSUE TITLE
Problems when drawing and firing bow?

### ISSUE THREAD

**Issue by josephrooks** [Cavallium/CoordinatesObfuscator#3]
I'm getting some errors in the console whenever I draw back a bow or fire a bow. Here's a sample:

https://paste.gg/p/anonymous/77aa9815890e49c4a51f3463d5a5bd3f

Running the final Paper 1.15.2 release and Coordinate Obfuscator 1.3.4

**Comment by Cavallium** [comment]
Fixed in the last commit.
