### ISSUE TITLE
Coordinates revealed for a short time upon login to players with high-latency connections

### ISSUE THREAD

**Issue by Sabinno** [Cavallium/CoordinatesObfuscator#4]
I had a friend in another country log in to my server today, and he realized that the coordinate obfuscator does not apply until *after* login. As his latency is extremely bad, he was able to get a good look at the coordinates for several consecutive seconds 
while the game loaded.

This isn't necessary easily reproducible, since you'd have to have an extremely high-latency connection to do it. I couldn't reproduce it myself for that reason. But I have attached a screenshot from the player in question, and verified that his coordinates shown there are, in fact, the real ones.

![bug report](https://user-images.githubusercontent.com/6600505/95020566-edf39c00-0639-11eb-91b6-e8f76b385504.jpg)

Is there, realistically, a good way to fix this?

**Comment by Cavallium** [comment]
Maybe I forgot to intercept one of the packets sent at login, or ProtocolLib misses a packet.
I'll fix it, but it might take some time.

**Comment by Cavallium** [comment]
Can you try with the latest version?
